-- Migration 002: Ensure drivers table has all required columns
-- Adds missing columns to drivers table safely (will not fail if column already exists)

ALTER TABLE drivers
    ADD COLUMN IF NOT EXISTS full_name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS date_of_birth DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS driver_address TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS pin_code VARCHAR(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS license_no VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS license_doe DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS license_type VARCHAR(50) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS adhaar_card_no VARCHAR(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS pan_card_no VARCHAR(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS photo VARCHAR(10) DEFAULT 'NO',
    ADD COLUMN IF NOT EXISTS driver_city VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS agency_name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS second_number VARCHAR(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS userType VARCHAR(50) DEFAULT NULL;
