-- Migration 003: Ensure cars table has all required columns

ALTER TABLE cars
    ADD COLUMN IF NOT EXISTS owner_id VARCHAR(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS vehicle_type VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS vehicle_name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS fuel_type VARCHAR(50) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS rc_no VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS rc_name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS rc_manufecture_date DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS insurance_number VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS insurance_doe DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS puc_doi DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS puc_doe DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS texi_permit_no VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS texi_permit_doi DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS texi_permit_doe DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS fitness_certificate_no VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS fitness_certificate_doi DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS fitness_certificate_doe DATE DEFAULT NULL;
