-- Migration 004: Ensure users table has all required columns

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS booking_number VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS pincode VARCHAR(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS agency_name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS account_type VARCHAR(50) DEFAULT NULL;
