ALTER TABLE drivers MODIFY COLUMN status VARCHAR(50) DEFAULT 'inactive';
ALTER TABLE vendors MODIFY COLUMN status VARCHAR(50) DEFAULT 'inactive';

ALTER TABLE drivers ADD COLUMN block_reason VARCHAR(255) DEFAULT NULL;
ALTER TABLE drivers ADD COLUMN blocked_at DATETIME DEFAULT NULL;

ALTER TABLE vendors ADD COLUMN block_reason VARCHAR(255) DEFAULT NULL;
ALTER TABLE vendors ADD COLUMN blocked_at DATETIME DEFAULT NULL;

